import Foundation

/// Lightweight, dependency-free localization for the Clawdesk UI.
///
/// Strings are keyed by their English source text. The settings picker offers
/// the same locales as the upstream product; untranslated keys fall back to
/// English instead of blocking the switch.
public enum Localization {
    public static func string(_ key: String, language: String) -> String? {
        tables[language]?[key]
    }

    public static let supportedLanguages = ["en", "zh-Hans", "zh-Hant", "ja", "ko", "es"]

    private static let tables: [String: [String: String]] = [
        "zh-Hans": [
            "General": "通用",
            "Agents": "代理",
            "Permissions": "权限",
            "Remote": "远程",
            "Remote SSH": "远程 SSH",
            "About": "关于",
            "Theme": "主题",
            "Idle visual": "待机动画",
            "Import theme…": "导入主题…",
            "Remove custom theme": "移除自定义主题",
            "Mini Mode": "迷你模式",
            "Mini mode": "迷你模式",
            "Exit Mini Mode": "退出迷你模式",
            "Low-power animations": "低功耗动画",
            "Sound effects": "音效",
            "Launch at login": "登录时启动",
            "Do Not Disturb": "勿扰模式",
            "Wake Clawdesk": "唤醒 Clawdesk",
            "Desktop pet": "桌面宠物",
            "Pet size": "宠物大小",
            "Free roam": "自由漫游",
            "Choose area…": "划定活动区域…",
            "Remove custom area": "移除自定义区域",
            "Confirm": "确认",
            "Cancel": "取消",
            "Interface language": "界面语言",
            "System default": "跟随系统",
            "Reset position": "重置位置",
            "Open Dashboard": "打开仪表盘",
            "Sessions": "会话",
            "Settings…": "设置…",
            "Quit Clawdesk": "退出 Clawdesk",
            "Clawdesk Dashboard": "Clawdesk 仪表盘",
            "Live sessions": "实时会话",
            "No active sessions": "暂无活动会话",
            "Start a supported coding agent to see it here.": "启动受支持的编码代理后会显示在这里。",
            "Recent events": "最近事件",
            "Waiting for local agent events…": "等待本地代理事件…",
            "Focus": "聚焦",
            "live session": "个实时会话",
            "live sessions": "个实时会话",
            "subagent": "个子代理",
            "subagents": "个子代理",
            "permission request pending": "个权限请求待处理",
            "Clawdesk Settings": "Clawdesk 设置",
            "Permission review": "权限审核",
            "Answer in Codex": "在 Codex 中回答",
            "Allow": "允许",
            "Deny": "拒绝",
            "A native macOS desktop companion for coding agents.": "原生 macOS 编码代理桌面伴侣。",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 构建 · 无内嵌浏览器运行时"
        ],
        "zh-Hant": [
            "General": "一般",
            "Agents": "代理",
            "Permissions": "權限",
            "Remote": "遠端",
            "Remote SSH": "遠端 SSH",
            "About": "關於",
            "Theme": "主題",
            "Idle visual": "待機動畫",
            "Import theme…": "匯入主題…",
            "Remove custom theme": "移除自訂主題",
            "Mini Mode": "迷你模式",
            "Mini mode": "迷你模式",
            "Exit Mini Mode": "退出迷你模式",
            "Low-power animations": "低功耗動畫",
            "Sound effects": "音效",
            "Launch at login": "登入時啟動",
            "Do Not Disturb": "勿擾模式",
            "Wake Clawdesk": "喚醒 Clawdesk",
            "Desktop pet": "桌面寵物",
            "Pet size": "寵物大小",
            "Free roam": "自由漫遊",
            "Choose area…": "劃定活動區域…",
            "Remove custom area": "移除自訂區域",
            "Confirm": "確認",
            "Cancel": "取消",
            "Interface language": "介面語言",
            "System default": "跟隨系統",
            "Reset position": "重置位置",
            "Open Dashboard": "開啟儀表板",
            "Sessions": "會話",
            "Settings…": "設定…",
            "Quit Clawdesk": "結束 Clawdesk",
            "Clawdesk Dashboard": "Clawdesk 儀表板",
            "Live sessions": "即時會話",
            "No active sessions": "暫無活動會話",
            "Start a supported coding agent to see it here.": "啟動受支援的編碼代理後會顯示在這裡。",
            "Recent events": "最近事件",
            "Waiting for local agent events…": "等待本地代理事件…",
            "Focus": "聚焦",
            "live session": "個即時會話",
            "live sessions": "個即時會話",
            "subagent": "個子代理",
            "subagents": "個子代理",
            "permission request pending": "個權限請求待處理",
            "Clawdesk Settings": "Clawdesk 設定",
            "Permission review": "權限審核",
            "Answer in Codex": "在 Codex 中回答",
            "Allow": "允許",
            "Deny": "拒絕",
            "A native macOS desktop companion for coding agents.": "原生 macOS 編碼代理桌面伴侶。",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 建置 · 無內嵌瀏覽器運行時"
        ],
        "ja": [
            "General": "一般",
            "Agents": "エージェント",
            "Permissions": "権限",
            "Remote": "リモート",
            "Remote SSH": "リモート SSH",
            "About": "情報",
            "Theme": "テーマ",
            "Idle visual": "待機アニメ",
            "Import theme…": "テーマを読み込む…",
            "Remove custom theme": "カスタムテーマを削除",
            "Mini Mode": "ミニモード",
            "Mini mode": "ミニモード",
            "Exit Mini Mode": "ミニモードを終了",
            "Low-power animations": "省電力アニメーション",
            "Sound effects": "サウンド",
            "Launch at login": "ログイン時に起動",
            "Do Not Disturb": "おやすみモード",
            "Wake Clawdesk": "Clawdesk を起こす",
            "Desktop pet": "デスクトップペット",
            "Pet size": "ペットのサイズ",
            "Free roam": "自由に歩き回る",
            "Choose area…": "活動エリアを選択…",
            "Remove custom area": "カスタムエリアを削除",
            "Confirm": "確定",
            "Cancel": "キャンセル",
            "Interface language": "表示言語",
            "System default": "システム既定",
            "Reset position": "位置をリセット",
            "Open Dashboard": "ダッシュボードを開く",
            "Sessions": "セッション",
            "Settings…": "設定…",
            "Quit Clawdesk": "Clawdesk を終了",
            "Clawdesk Dashboard": "Clawdesk ダッシュボード",
            "Live sessions": "ライブセッション",
            "No active sessions": "アクティブなセッションはありません",
            "Start a supported coding agent to see it here.": "対応するコーディングエージェントを起動すると表示されます。",
            "Recent events": "最近のイベント",
            "Waiting for local agent events…": "ローカルエージェントのイベントを待機中…",
            "Focus": "フォーカス",
            "live session": "件のライブセッション",
            "live sessions": "件のライブセッション",
            "subagent": "件のサブエージェント",
            "subagents": "件のサブエージェント",
            "permission request pending": "件の権限リクエスト待ち",
            "Clawdesk Settings": "Clawdesk 設定",
            "Permission review": "権限の確認",
            "Answer in Codex": "Codex で回答",
            "Allow": "許可",
            "Deny": "拒否",
            "A native macOS desktop companion for coding agents.": "ネイティブ macOS のコーディングエージェント用デスクトップコンパニオン。",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 製 · ブラウザランタイム非内蔵"
        ],
        "ko": [
            "General": "일반",
            "Agents": "에이전트",
            "Permissions": "권한",
            "Remote": "원격",
            "Remote SSH": "원격 SSH",
            "About": "정보",
            "Theme": "테마",
            "Idle visual": "대기 애니메이션",
            "Import theme…": "테마 가져오기…",
            "Remove custom theme": "사용자 테마 제거",
            "Mini Mode": "미니 모드",
            "Mini mode": "미니 모드",
            "Exit Mini Mode": "미니 모드 종료",
            "Low-power animations": "저전력 애니메이션",
            "Sound effects": "효과음",
            "Launch at login": "로그인 시 시작",
            "Do Not Disturb": "방해 금지",
            "Wake Clawdesk": "Clawdesk 깨우기",
            "Desktop pet": "데스크톱 펫",
            "Pet size": "펫 크기",
            "Free roam": "자유 이동",
            "Choose area…": "활동 영역 선택…",
            "Remove custom area": "사용자 영역 제거",
            "Confirm": "확인",
            "Cancel": "취소",
            "Interface language": "인터페이스 언어",
            "System default": "시스템 기본값",
            "Reset position": "위치 재설정",
            "Open Dashboard": "대시보드 열기",
            "Sessions": "세션",
            "Settings…": "설정…",
            "Quit Clawdesk": "Clawdesk 종료",
            "Clawdesk Dashboard": "Clawdesk 대시보드",
            "Live sessions": "라이브 세션",
            "No active sessions": "활성 세션 없음",
            "Start a supported coding agent to see it here.": "지원되는 코딩 에이전트를 시작하면 여기에 표시됩니다.",
            "Recent events": "최근 이벤트",
            "Waiting for local agent events…": "로컬 에이전트 이벤트 대기 중…",
            "Focus": "포커스",
            "live session": "개 라이브 세션",
            "live sessions": "개 라이브 세션",
            "subagent": "개 하위 에이전트",
            "subagents": "개 하위 에이전트",
            "permission request pending": "건의 권한 요청 대기 중",
            "Clawdesk Settings": "Clawdesk 설정",
            "Permission review": "권한 검토",
            "Answer in Codex": "Codex에서 답변",
            "Allow": "허용",
            "Deny": "거부",
            "A native macOS desktop companion for coding agents.": "코딩 에이전트용 네이티브 macOS 데스크톱 컴패니언.",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 기반 · 브라우저 런타임 미내장"
        ],
        "es": [
            "General": "General",
            "Agents": "Agentes",
            "Permissions": "Permisos",
            "Remote": "Remoto",
            "Remote SSH": "SSH remoto",
            "About": "Acerca de",
            "Theme": "Tema",
            "Idle visual": "Animación de espera",
            "Import theme…": "Importar tema…",
            "Remove custom theme": "Quitar tema personalizado",
            "Mini Mode": "Modo mini",
            "Mini mode": "Modo mini",
            "Exit Mini Mode": "Salir del modo mini",
            "Low-power animations": "Animaciones de bajo consumo",
            "Sound effects": "Efectos de sonido",
            "Launch at login": "Iniciar al iniciar sesión",
            "Do Not Disturb": "No molestar",
            "Wake Clawdesk": "Despertar Clawdesk",
            "Desktop pet": "Mascota de escritorio",
            "Pet size": "Tamaño de la mascota",
            "Free roam": "Deambular libremente",
            "Choose area…": "Elegir área…",
            "Remove custom area": "Quitar área personalizada",
            "Confirm": "Confirmar",
            "Cancel": "Cancelar",
            "Interface language": "Idioma de la interfaz",
            "System default": "Predeterminado del sistema",
            "Reset position": "Restablecer posición",
            "Open Dashboard": "Abrir panel",
            "Sessions": "Sesiones",
            "Settings…": "Ajustes…",
            "Quit Clawdesk": "Salir de Clawdesk",
            "Clawdesk Dashboard": "Panel de Clawdesk",
            "Live sessions": "Sesiones activas",
            "No active sessions": "Sin sesiones activas",
            "Start a supported coding agent to see it here.": "Inicia un agente de codificación compatible para verlo aquí.",
            "Recent events": "Eventos recientes",
            "Waiting for local agent events…": "Esperando eventos del agente local…",
            "Focus": "Enfocar",
            "live session": "sesión activa",
            "live sessions": "sesiones activas",
            "subagent": "subagente",
            "subagents": "subagentes",
            "permission request pending": "solicitud de permiso pendiente",
            "Clawdesk Settings": "Ajustes de Clawdesk",
            "Permission review": "Revisión de permisos",
            "Answer in Codex": "Responder en Codex",
            "Allow": "Permitir",
            "Deny": "Denegar",
            "A native macOS desktop companion for coding agents.": "Un compañero de escritorio nativo de macOS para agentes de codificación.",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Hecho con Swift + AppKit/SwiftUI · sin navegador integrado"
        ]
    ]
}
