import Foundation

/// Lightweight, dependency-free localization for the Clawdesk UI.
///
/// Strings are keyed by their English source text. The settings picker offers
/// the same locales as the upstream product; untranslated keys fall back to
/// English instead of blocking the switch.
public enum Localization {
    public static func string(_ key: String, language: String) -> String? {
        tables[language]?[key]
    }

    public static let supportedLanguages = ["en", "zh-Hans", "zh-Hant", "ja", "ko", "es"]

    private static let tables: [String: [String: String]] = [
        "zh-Hans": [
            "General": "通用",
            "Agents": "代理",
            "Permissions": "权限",
            "Remote": "远程",
            "Remote SSH": "远程 SSH",
            "About": "关于",
            "Theme": "主题",
            "Idle visual": "待机动画",
            "Import theme…": "导入主题…",
            "Remove custom theme": "移除自定义主题",
            "Mini Mode": "迷你模式",
            "Mini mode": "迷你模式",
            "Exit Mini Mode": "退出迷你模式",
            "Low-power animations": "低功耗动画",
            "Sound effects": "音效",
            "Launch at login": "登录时启动",
            "Do Not Disturb": "勿扰模式",
            "Wake Clawdesk": "唤醒 Clawdesk",
            "Desktop pet": "桌面宠物",
            "Pet size": "宠物大小",
            "Free roam": "自由漫游",
            "Choose area…": "划定活动区域…",
            "Remove custom area": "移除自定义区域",
            "Confirm": "确认",
            "Cancel": "取消",
            "Doctor": "诊断",
            "Run checks": "运行检查",
            "Fix": "修复",
            "OK": "正常",
            "Not installed": "未安装",
            "Needs repair": "需要修复",
            "Not checked": "未检查",
            "Quota ring": "配额环",
            "Collect local Claude usage": "收集本地 Claude 用量",
            "Agent integrations": "代理集成",
            "Install": "安装",
            "Re-sync": "重新同步",
            "Remove": "移除",
            "State-only": "仅状态",
            "Ready": "就绪",
            "Permission handling": "权限处理",
            "Show pop-up bubbles": "显示弹窗气泡",
            "Local approval": "本地审批",
            "Keyboard shortcuts": "键盘快捷键",
            "Allow latest request": "允许最新请求",
            "Deny latest request": "拒绝最新请求",
            "Local bridge": "本地桥接",
            "Endpoint": "端点",
            "Mobile companion (read-only LAN)": "移动伴侣（只读局域网）",
            "Enable LAN bridge": "启用局域网桥接",
            "LAN port": "局域网端口",
            "Rotate token": "轮换令牌",
            "Remote notifications": "远程通知",
            "Enable configured channels": "启用已配置的通道",
            "Telegram remote approval": "Telegram 远程审批",
            "Mirror eligible permission requests": "镜像符合资格的权限请求",
            "Target chat ID": "目标会话 ID",
            "Allowed approver user ID": "允许的审批人用户 ID",
            "Remote card timeout": "远程卡片超时",
            "Save Telegram approval": "保存 Telegram 审批",
            "Feishu / Lark interactive approval": "飞书 / Lark 交互式审批",
            "Platform": "平台",
            "Feishu (China)": "飞书（中国）",
            "Lark (International)": "Lark（国际）",
            "App ID (cli_…)": "应用 ID (cli_…)",
            "Approver ID": "审批人 ID",
            "Approver ID type": "审批人 ID 类型",
            "Connection timeout": "连接超时",
            "Save Feishu / Lark approval": "保存飞书 / Lark 审批",
            "Updates": "更新",
            "Check GitHub releases": "检查 GitHub 发布",
            "Download package": "下载安装包",
            "Checking…": "检查中…",
            "Check for Updates…": "检查更新…",
            "Permission automation": "权限自动化",
            "Off": "关闭",
            "Auto-allow read-only tools": "自动允许只读工具",
            "Unattended (fail closed)": "无人值守（失败即拒绝）",
            "Interface language": "界面语言",
            "System default": "跟随系统",
            "Reset position": "重置位置",
            "Open Dashboard": "打开仪表盘",
            "Sessions": "会话",
            "Settings…": "设置…",
            "Quit Clawdesk": "退出 Clawdesk",
            "Clawdesk Dashboard": "Clawdesk 仪表盘",
            "Live sessions": "实时会话",
            "No active sessions": "暂无活动会话",
            "Start a supported coding agent to see it here.": "启动受支持的编码代理后会显示在这里。",
            "Recent events": "最近事件",
            "Waiting for local agent events…": "等待本地代理事件…",
            "Focus": "聚焦",
            "live session": "个实时会话",
            "live sessions": "个实时会话",
            "subagent": "个子代理",
            "subagents": "个子代理",
            "permission request pending": "个权限请求待处理",
            "Clawdesk Settings": "Clawdesk 设置",
            "Permission review": "权限审核",
            "Answer in Codex": "在 Codex 中回答",
            "Allow": "允许",
            "Deny": "拒绝",
            "A native macOS desktop companion for coding agents.": "原生 macOS 编码代理桌面伴侣。",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 构建 · 无内嵌浏览器运行时"
        ],
        "zh-Hant": [
            "General": "一般",
            "Agents": "代理",
            "Permissions": "權限",
            "Remote": "遠端",
            "Remote SSH": "遠端 SSH",
            "About": "關於",
            "Theme": "主題",
            "Idle visual": "待機動畫",
            "Import theme…": "匯入主題…",
            "Remove custom theme": "移除自訂主題",
            "Mini Mode": "迷你模式",
            "Mini mode": "迷你模式",
            "Exit Mini Mode": "退出迷你模式",
            "Low-power animations": "低功耗動畫",
            "Sound effects": "音效",
            "Launch at login": "登入時啟動",
            "Do Not Disturb": "勿擾模式",
            "Wake Clawdesk": "喚醒 Clawdesk",
            "Desktop pet": "桌面寵物",
            "Pet size": "寵物大小",
            "Free roam": "自由漫遊",
            "Choose area…": "劃定活動區域…",
            "Remove custom area": "移除自訂區域",
            "Confirm": "確認",
            "Cancel": "取消",
            "Doctor": "診斷",
            "Run checks": "執行檢查",
            "Fix": "修復",
            "OK": "正常",
            "Not installed": "未安裝",
            "Needs repair": "需要修復",
            "Not checked": "未檢查",
            "Quota ring": "配額環",
            "Collect local Claude usage": "收集本機 Claude 用量",
            "Agent integrations": "代理整合",
            "Install": "安裝",
            "Re-sync": "重新同步",
            "Remove": "移除",
            "State-only": "僅狀態",
            "Ready": "就緒",
            "Permission handling": "權限處理",
            "Show pop-up bubbles": "顯示彈窗氣泡",
            "Local approval": "本地審批",
            "Keyboard shortcuts": "鍵盤快捷鍵",
            "Allow latest request": "允許最新請求",
            "Deny latest request": "拒絕最新請求",
            "Local bridge": "本機橋接",
            "Endpoint": "端點",
            "Mobile companion (read-only LAN)": "行動伴侶（唯讀區域網路）",
            "Enable LAN bridge": "啟用區域網路橋接",
            "LAN port": "區域網路連接埠",
            "Rotate token": "輪換權杖",
            "Remote notifications": "遠端通知",
            "Enable configured channels": "啟用已設定的通道",
            "Telegram remote approval": "Telegram 遠端審批",
            "Mirror eligible permission requests": "鏡像符合資格的權限請求",
            "Target chat ID": "目標聊天 ID",
            "Allowed approver user ID": "允許的審批人使用者 ID",
            "Remote card timeout": "遠端卡片逾時",
            "Save Telegram approval": "儲存 Telegram 審批",
            "Feishu / Lark interactive approval": "飛書 / Lark 互動式審批",
            "Platform": "平台",
            "Feishu (China)": "飛書（中國）",
            "Lark (International)": "Lark（國際）",
            "App ID (cli_…)": "應用程式 ID (cli_…)",
            "Approver ID": "審批人 ID",
            "Approver ID type": "審批人 ID 類型",
            "Connection timeout": "連線逾時",
            "Save Feishu / Lark approval": "儲存飛書 / Lark 審批",
            "Updates": "更新",
            "Check GitHub releases": "檢查 GitHub 發行",
            "Download package": "下載安裝套件",
            "Checking…": "檢查中…",
            "Check for Updates…": "檢查更新…",
            "Permission automation": "權限自動化",
            "Off": "關閉",
            "Auto-allow read-only tools": "自動允許唯讀工具",
            "Unattended (fail closed)": "無人值守（失敗即拒絕）",
            "Interface language": "介面語言",
            "System default": "跟隨系統",
            "Reset position": "重置位置",
            "Open Dashboard": "開啟儀表板",
            "Sessions": "會話",
            "Settings…": "設定…",
            "Quit Clawdesk": "結束 Clawdesk",
            "Clawdesk Dashboard": "Clawdesk 儀表板",
            "Live sessions": "即時會話",
            "No active sessions": "暫無活動會話",
            "Start a supported coding agent to see it here.": "啟動受支援的編碼代理後會顯示在這裡。",
            "Recent events": "最近事件",
            "Waiting for local agent events…": "等待本地代理事件…",
            "Focus": "聚焦",
            "live session": "個即時會話",
            "live sessions": "個即時會話",
            "subagent": "個子代理",
            "subagents": "個子代理",
            "permission request pending": "個權限請求待處理",
            "Clawdesk Settings": "Clawdesk 設定",
            "Permission review": "權限審核",
            "Answer in Codex": "在 Codex 中回答",
            "Allow": "允許",
            "Deny": "拒絕",
            "A native macOS desktop companion for coding agents.": "原生 macOS 編碼代理桌面伴侶。",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 建置 · 無內嵌瀏覽器運行時"
        ],
        "ja": [
            "General": "一般",
            "Agents": "エージェント",
            "Permissions": "権限",
            "Remote": "リモート",
            "Remote SSH": "リモート SSH",
            "About": "情報",
            "Theme": "テーマ",
            "Idle visual": "待機アニメ",
            "Import theme…": "テーマを読み込む…",
            "Remove custom theme": "カスタムテーマを削除",
            "Mini Mode": "ミニモード",
            "Mini mode": "ミニモード",
            "Exit Mini Mode": "ミニモードを終了",
            "Low-power animations": "省電力アニメーション",
            "Sound effects": "サウンド",
            "Launch at login": "ログイン時に起動",
            "Do Not Disturb": "おやすみモード",
            "Wake Clawdesk": "Clawdesk を起こす",
            "Desktop pet": "デスクトップペット",
            "Pet size": "ペットのサイズ",
            "Free roam": "自由に歩き回る",
            "Choose area…": "活動エリアを選択…",
            "Remove custom area": "カスタムエリアを削除",
            "Confirm": "確定",
            "Cancel": "キャンセル",
            "Doctor": "診断",
            "Run checks": "チェックを実行",
            "Fix": "修復",
            "OK": "正常",
            "Not installed": "未インストール",
            "Needs repair": "修復が必要",
            "Not checked": "未チェック",
            "Quota ring": "クォータリング",
            "Collect local Claude usage": "ローカルの Claude 使用量を収集",
            "Agent integrations": "エージェント統合",
            "Install": "インストール",
            "Re-sync": "再同期",
            "Remove": "削除",
            "State-only": "状態のみ",
            "Ready": "準備完了",
            "Permission handling": "権限の処理",
            "Show pop-up bubbles": "ポップアップバブルを表示",
            "Local approval": "ローカル承認",
            "Keyboard shortcuts": "キーボードショートカット",
            "Allow latest request": "最新のリクエストを許可",
            "Deny latest request": "最新のリクエストを拒否",
            "Local bridge": "ローカルブリッジ",
            "Endpoint": "エンドポイント",
            "Mobile companion (read-only LAN)": "モバイルコンパニオン（読み取り専用LAN）",
            "Enable LAN bridge": "LANブリッジを有効化",
            "LAN port": "LANポート",
            "Rotate token": "トークンを再生成",
            "Remote notifications": "リモート通知",
            "Enable configured channels": "設定済みチャンネルを有効化",
            "Telegram remote approval": "Telegramリモート承認",
            "Mirror eligible permission requests": "対象の権限リクエストをミラー",
            "Target chat ID": "ターゲットチャットID",
            "Allowed approver user ID": "承認者ユーザーID",
            "Remote card timeout": "リモートカードのタイムアウト",
            "Save Telegram approval": "Telegram承認を保存",
            "Feishu / Lark interactive approval": "Feishu / Lark インタラクティブ承認",
            "Platform": "プラットフォーム",
            "Feishu (China)": "Feishu（中国）",
            "Lark (International)": "Lark（国際）",
            "App ID (cli_…)": "アプリID (cli_…)",
            "Approver ID": "承認者ID",
            "Approver ID type": "承認者IDタイプ",
            "Connection timeout": "接続タイムアウト",
            "Save Feishu / Lark approval": "Feishu / Lark承認を保存",
            "Updates": "更新",
            "Check GitHub releases": "GitHubリリースを確認",
            "Download package": "パッケージをダウンロード",
            "Checking…": "確認中…",
            "Check for Updates…": "更新を確認…",
            "Permission automation": "権限の自動化",
            "Off": "オフ",
            "Auto-allow read-only tools": "読み取り専用ツールを自動許可",
            "Unattended (fail closed)": "無人（フェイルクローズ）",
            "Interface language": "表示言語",
            "System default": "システム既定",
            "Reset position": "位置をリセット",
            "Open Dashboard": "ダッシュボードを開く",
            "Sessions": "セッション",
            "Settings…": "設定…",
            "Quit Clawdesk": "Clawdesk を終了",
            "Clawdesk Dashboard": "Clawdesk ダッシュボード",
            "Live sessions": "ライブセッション",
            "No active sessions": "アクティブなセッションはありません",
            "Start a supported coding agent to see it here.": "対応するコーディングエージェントを起動すると表示されます。",
            "Recent events": "最近のイベント",
            "Waiting for local agent events…": "ローカルエージェントのイベントを待機中…",
            "Focus": "フォーカス",
            "live session": "件のライブセッション",
            "live sessions": "件のライブセッション",
            "subagent": "件のサブエージェント",
            "subagents": "件のサブエージェント",
            "permission request pending": "件の権限リクエスト待ち",
            "Clawdesk Settings": "Clawdesk 設定",
            "Permission review": "権限の確認",
            "Answer in Codex": "Codex で回答",
            "Allow": "許可",
            "Deny": "拒否",
            "A native macOS desktop companion for coding agents.": "ネイティブ macOS のコーディングエージェント用デスクトップコンパニオン。",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 製 · ブラウザランタイム非内蔵"
        ],
        "ko": [
            "General": "일반",
            "Agents": "에이전트",
            "Permissions": "권한",
            "Remote": "원격",
            "Remote SSH": "원격 SSH",
            "About": "정보",
            "Theme": "테마",
            "Idle visual": "대기 애니메이션",
            "Import theme…": "테마 가져오기…",
            "Remove custom theme": "사용자 테마 제거",
            "Mini Mode": "미니 모드",
            "Mini mode": "미니 모드",
            "Exit Mini Mode": "미니 모드 종료",
            "Low-power animations": "저전력 애니메이션",
            "Sound effects": "효과음",
            "Launch at login": "로그인 시 시작",
            "Do Not Disturb": "방해 금지",
            "Wake Clawdesk": "Clawdesk 깨우기",
            "Desktop pet": "데스크톱 펫",
            "Pet size": "펫 크기",
            "Free roam": "자유 이동",
            "Choose area…": "활동 영역 선택…",
            "Remove custom area": "사용자 영역 제거",
            "Confirm": "확인",
            "Cancel": "취소",
            "Doctor": "진단",
            "Run checks": "검사 실행",
            "Fix": "수리",
            "OK": "정상",
            "Not installed": "설치 안 됨",
            "Needs repair": "수리 필요",
            "Not checked": "확인 안 됨",
            "Quota ring": "할당량 링",
            "Collect local Claude usage": "로컬 Claude 사용량 수집",
            "Agent integrations": "에이전트 통합",
            "Install": "설치",
            "Re-sync": "재동기화",
            "Remove": "제거",
            "State-only": "상태만",
            "Ready": "준비됨",
            "Permission handling": "권한 처리",
            "Show pop-up bubbles": "팝업 버블 표시",
            "Local approval": "로컬 승인",
            "Keyboard shortcuts": "키보드 단축키",
            "Allow latest request": "최신 요청 허용",
            "Deny latest request": "최신 요청 거부",
            "Local bridge": "로컬 브리지",
            "Endpoint": "엔드포인트",
            "Mobile companion (read-only LAN)": "모바일 컴패니언(읽기 전용 LAN)",
            "Enable LAN bridge": "LAN 브리지 활성화",
            "LAN port": "LAN 포트",
            "Rotate token": "토큰 회전",
            "Remote notifications": "원격 알림",
            "Enable configured channels": "설정된 채널 활성화",
            "Telegram remote approval": "Telegram 원격 승인",
            "Mirror eligible permission requests": "대상 권한 요청 미러링",
            "Target chat ID": "대상 채팅 ID",
            "Allowed approver user ID": "허용된 승인자 사용자 ID",
            "Remote card timeout": "원격 카드 시간 초과",
            "Save Telegram approval": "Telegram 승인 저장",
            "Feishu / Lark interactive approval": "Feishu / Lark 대화형 승인",
            "Platform": "플랫폼",
            "Feishu (China)": "Feishu(중국)",
            "Lark (International)": "Lark(국제)",
            "App ID (cli_…)": "앱 ID (cli_…)",
            "Approver ID": "승인자 ID",
            "Approver ID type": "승인자 ID 유형",
            "Connection timeout": "연결 시간 초과",
            "Save Feishu / Lark approval": "Feishu / Lark 승인 저장",
            "Updates": "업데이트",
            "Check GitHub releases": "GitHub 릴리스 확인",
            "Download package": "패키지 다운로드",
            "Checking…": "확인 중…",
            "Check for Updates…": "업데이트 확인…",
            "Permission automation": "권한 자동화",
            "Off": "끔",
            "Auto-allow read-only tools": "읽기 전용 도구 자동 허용",
            "Unattended (fail closed)": "무인 (실패 시 거부)",
            "Interface language": "인터페이스 언어",
            "System default": "시스템 기본값",
            "Reset position": "위치 재설정",
            "Open Dashboard": "대시보드 열기",
            "Sessions": "세션",
            "Settings…": "설정…",
            "Quit Clawdesk": "Clawdesk 종료",
            "Clawdesk Dashboard": "Clawdesk 대시보드",
            "Live sessions": "라이브 세션",
            "No active sessions": "활성 세션 없음",
            "Start a supported coding agent to see it here.": "지원되는 코딩 에이전트를 시작하면 여기에 표시됩니다.",
            "Recent events": "최근 이벤트",
            "Waiting for local agent events…": "로컬 에이전트 이벤트 대기 중…",
            "Focus": "포커스",
            "live session": "개 라이브 세션",
            "live sessions": "개 라이브 세션",
            "subagent": "개 하위 에이전트",
            "subagents": "개 하위 에이전트",
            "permission request pending": "건의 권한 요청 대기 중",
            "Clawdesk Settings": "Clawdesk 설정",
            "Permission review": "권한 검토",
            "Answer in Codex": "Codex에서 답변",
            "Allow": "허용",
            "Deny": "거부",
            "A native macOS desktop companion for coding agents.": "코딩 에이전트용 네이티브 macOS 데스크톱 컴패니언.",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Swift + AppKit/SwiftUI 기반 · 브라우저 런타임 미내장"
        ],
        "es": [
            "General": "General",
            "Agents": "Agentes",
            "Permissions": "Permisos",
            "Remote": "Remoto",
            "Remote SSH": "SSH remoto",
            "About": "Acerca de",
            "Theme": "Tema",
            "Idle visual": "Animación de espera",
            "Import theme…": "Importar tema…",
            "Remove custom theme": "Quitar tema personalizado",
            "Mini Mode": "Modo mini",
            "Mini mode": "Modo mini",
            "Exit Mini Mode": "Salir del modo mini",
            "Low-power animations": "Animaciones de bajo consumo",
            "Sound effects": "Efectos de sonido",
            "Launch at login": "Iniciar al iniciar sesión",
            "Do Not Disturb": "No molestar",
            "Wake Clawdesk": "Despertar Clawdesk",
            "Desktop pet": "Mascota de escritorio",
            "Pet size": "Tamaño de la mascota",
            "Free roam": "Deambular libremente",
            "Choose area…": "Elegir área…",
            "Remove custom area": "Quitar área personalizada",
            "Confirm": "Confirmar",
            "Cancel": "Cancelar",
            "Doctor": "Diagnóstico",
            "Run checks": "Ejecutar comprobaciones",
            "Fix": "Reparar",
            "OK": "Correcto",
            "Not installed": "No instalado",
            "Needs repair": "Necesita reparación",
            "Not checked": "No comprobado",
            "Quota ring": "Anillo de cuota",
            "Collect local Claude usage": "Recopilar uso local de Claude",
            "Agent integrations": "Integraciones de agentes",
            "Install": "Instalar",
            "Re-sync": "Resincronizar",
            "Remove": "Quitar",
            "State-only": "Solo estado",
            "Ready": "Listo",
            "Permission handling": "Manejo de permisos",
            "Show pop-up bubbles": "Mostrar burbujas emergentes",
            "Local approval": "Aprobación local",
            "Keyboard shortcuts": "Atajos de teclado",
            "Allow latest request": "Permitir última solicitud",
            "Deny latest request": "Denegar última solicitud",
            "Local bridge": "Puente local",
            "Endpoint": "Punto de conexión",
            "Mobile companion (read-only LAN)": "Compañero móvil (LAN de solo lectura)",
            "Enable LAN bridge": "Activar puente LAN",
            "LAN port": "Puerto LAN",
            "Rotate token": "Rotar token",
            "Remote notifications": "Notificaciones remotas",
            "Enable configured channels": "Activar canales configurados",
            "Telegram remote approval": "Aprobación remota por Telegram",
            "Mirror eligible permission requests": "Replicar solicitudes de permiso elegibles",
            "Target chat ID": "ID de chat de destino",
            "Allowed approver user ID": "ID de usuario aprobador permitido",
            "Remote card timeout": "Tiempo de espera de la tarjeta remota",
            "Save Telegram approval": "Guardar aprobación de Telegram",
            "Feishu / Lark interactive approval": "Aprobación interactiva Feishu / Lark",
            "Platform": "Plataforma",
            "Feishu (China)": "Feishu (China)",
            "Lark (International)": "Lark (Internacional)",
            "App ID (cli_…)": "ID de app (cli_…)",
            "Approver ID": "ID de aprobador",
            "Approver ID type": "Tipo de ID de aprobador",
            "Connection timeout": "Tiempo de espera de conexión",
            "Save Feishu / Lark approval": "Guardar aprobación de Feishu / Lark",
            "Updates": "Actualizaciones",
            "Check GitHub releases": "Buscar versiones de GitHub",
            "Download package": "Descargar paquete",
            "Checking…": "Comprobando…",
            "Check for Updates…": "Buscar actualizaciones…",
            "Permission automation": "Automatización de permisos",
            "Off": "Desactivado",
            "Auto-allow read-only tools": "Permitir automáticamente herramientas de solo lectura",
            "Unattended (fail closed)": "Sin supervisión (fallo cerrado)",
            "Interface language": "Idioma de la interfaz",
            "System default": "Predeterminado del sistema",
            "Reset position": "Restablecer posición",
            "Open Dashboard": "Abrir panel",
            "Sessions": "Sesiones",
            "Settings…": "Ajustes…",
            "Quit Clawdesk": "Salir de Clawdesk",
            "Clawdesk Dashboard": "Panel de Clawdesk",
            "Live sessions": "Sesiones activas",
            "No active sessions": "Sin sesiones activas",
            "Start a supported coding agent to see it here.": "Inicia un agente de codificación compatible para verlo aquí.",
            "Recent events": "Eventos recientes",
            "Waiting for local agent events…": "Esperando eventos del agente local…",
            "Focus": "Enfocar",
            "live session": "sesión activa",
            "live sessions": "sesiones activas",
            "subagent": "subagente",
            "subagents": "subagentes",
            "permission request pending": "solicitud de permiso pendiente",
            "Clawdesk Settings": "Ajustes de Clawdesk",
            "Permission review": "Revisión de permisos",
            "Answer in Codex": "Responder en Codex",
            "Allow": "Permitir",
            "Deny": "Denegar",
            "A native macOS desktop companion for coding agents.": "Un compañero de escritorio nativo de macOS para agentes de codificación.",
            "Built in Swift + AppKit/SwiftUI · no embedded browser runtime": "Hecho con Swift + AppKit/SwiftUI · sin navegador integrado"
        ]
    ]
}
